"""milestone3_instagram_conversation_domain

Revision ID: bba02cf2ec16
Revises: f89bb9ba59b6
Create Date: 2026-04-10 19:43:09.533585

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bba02cf2ec16'
down_revision: str | None = 'f89bb9ba59b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=50), server_default=sa.text("'meta'"), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_id_hash', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id_hash')
    )
    op.create_index('ix_webhook_events_event_id_hash', 'webhook_events', ['event_id_hash'], unique=True)
    op.create_index('ix_webhook_events_processed', 'webhook_events', ['processed'], unique=False)
    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_workspace_id', 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('instagram_accounts',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('instagram_account_id', sa.String(length=128), nullable=False),
    sa.Column('instagram_username', sa.String(length=255), nullable=False),
    sa.Column('facebook_page_id', sa.String(length=128), nullable=True),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_reply_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reply_mode', sa.Enum('automatic', 'approval_required', 'human_only', name='reply_mode'), server_default=sa.text("'automatic'"), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), server_default=sa.text('0.75'), nullable=False),
    sa.Column('business_hours_only', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_accounts_instagram_account_id'), 'instagram_accounts', ['instagram_account_id'], unique=True)
    op.create_index('ix_instagram_accounts_workspace_id', 'instagram_accounts', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('instagram_account_id', sa.UUID(), nullable=False),
    sa.Column('customer_ig_user_id', sa.String(length=128), nullable=False),
    sa.Column('customer_username', sa.String(length=255), nullable=True),
    sa.Column('customer_display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('open', 'pending', 'closed', 'handoff', name='conversation_status'), server_default=sa.text("'open'"), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ai_paused', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_account_id', 'customer_ig_user_id', name='uq_conversation_account_customer')
    )
    op.create_index('ix_conversations_assigned_user_id', 'conversations', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_ig_user_id'), 'conversations', ['customer_ig_user_id'], unique=False)
    op.create_index('ix_conversations_last_message_at', 'conversations', ['last_message_at'], unique=False)
    op.create_index('ix_conversations_status', 'conversations', ['status'], unique=False)
    op.create_index('ix_conversations_workspace_id', 'conversations', ['workspace_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('trigger_message_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'skipped', name='ai_run_status'), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt_version', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('replied', 'escalated', 'skipped', name='ai_decision'), nullable=True),
    sa.Column('generated_text', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_runs_conversation_id', 'ai_runs', ['conversation_id'], unique=False)
    op.create_index('ix_ai_runs_workspace_id', 'ai_runs', ['workspace_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('instagram_account_id', sa.UUID(), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('sender_type', sa.Enum('customer', 'ai', 'human', 'system', name='sender_type'), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction'), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'image', 'story_reply', 'attachment', 'system', name='message_type'), server_default=sa.text("'text'"), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reply_to_message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('received', 'queued', 'sent', 'failed', name='message_status'), server_default=sa.text("'received'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_external_message_id', 'messages', ['external_message_id'], unique=False)
    op.create_index('ix_messages_workspace_id', 'messages', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_workspace_id', table_name='messages')
    op.drop_index('ix_messages_external_message_id', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.execute('DROP TYPE IF EXISTS message_status;')
    op.execute('DROP TYPE IF EXISTS message_type;')
    op.execute('DROP TYPE IF EXISTS message_direction;')
    op.execute('DROP TYPE IF EXISTS sender_type;')
    op.drop_index('ix_ai_runs_workspace_id', table_name='ai_runs')
    op.drop_index('ix_ai_runs_conversation_id', table_name='ai_runs')
    op.drop_table('ai_runs')
    op.execute('DROP TYPE IF EXISTS ai_decision;')
    op.execute('DROP TYPE IF EXISTS ai_run_status;')
    op.drop_index('ix_conversations_workspace_id', table_name='conversations')
    op.drop_index('ix_conversations_status', table_name='conversations')
    op.drop_index('ix_conversations_last_message_at', table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_ig_user_id'), table_name='conversations')
    op.drop_index('ix_conversations_assigned_user_id', table_name='conversations')
    op.drop_table('conversations')
    op.execute('DROP TYPE IF EXISTS conversation_status;')
    op.drop_index('ix_instagram_accounts_workspace_id', table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_instagram_account_id'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    op.execute('DROP TYPE IF EXISTS reply_mode;')
    op.drop_index('ix_audit_logs_workspace_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_webhook_events_processed', table_name='webhook_events')
    op.drop_index('ix_webhook_events_event_id_hash', table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
